[package]
name = "stwo_verifier_utils"
version = "0.1.0"
edition = "2024_07"

[lib]
casm = true

[features]
poseidon252_verifier = []
qm31_opcode = []
blake_outputs_packing = []
poseidon_outputs_packing = []

[tool]
cairo-lint.workspace = true

[tool.fmt]
sort-module-level-items = true

[dependencies]
bounded_int = { path = "../bounded_int" }

[dev-dependencies]
cairo_test = "2.12.2"
