[package]
name = "dev-utils"
version.workspace = true
edition.workspace = true

[dependencies]
cairo-air.workspace = true
clap.workspace = true
serde.workspace = true
starknet-ff.workspace = true
sonic-rs.workspace = true
stwo-cairo-adapter = { path = "../adapter", features = ["std"] }
stwo-cairo-serialize.workspace = true
stwo.workspace = true
stwo_cairo_prover = { workspace = true, features = ["relation-tracker"] }
stwo-constraint-framework.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
tracing.workspace = true
log.workspace = true
regex = "1.11.1"
serde_json.workspace = true
cairo-prove = { path = "../../../cairo-prove" }
cairo-vm.workspace = true
cairo-lang-runner = { git = "https://github.com/starkware-libs/cairo.git", rev = "5cc466a" }
cairo-lang-executable = { git = "https://github.com/starkware-libs/cairo.git", rev = "5cc466a" }
rayon.workspace = true
itertools.workspace = true