[crate_roots]
"bounded_int" = "../../bounded_int/src"
"stwo_cairo_air" = "../../cairo_air/src"
"stwo_constraint_framework" = "../../constraint_framework/src"
"stwo_verifier_core" = "../../verifier_core/src"
"stwo_verifier_utils" = "../../verifier_utils/src"
"stwo_cairo_verifier" = "../../cairo_verifier/src"
"stwo_cairo_verifier_mock" = "../../cairo_verifier_mock/src"

[config.global]
edition = "2024_07"
version = "0.1.0"
cfg_set = [[
    "target",
    "lib",
]]

[config.global.dependencies.bounded_int]
discriminator = "bounded_int"

[config.global.dependencies.stwo_cairo_air]
discriminator = "stwo_cairo_air"

[config.global.dependencies.stwo_constraint_framework]
discriminator = "stwo_constraint_framework"

[config.global.dependencies.stwo_verifier_core]
discriminator = "stwo_verifier_core"

[config.global.dependencies.stwo_verifier_utils]
discriminator = "stwo_verifier_utils"

[config.global.experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false
user_defined_inline_macros = false

[config.override."bounded_int"]
name = "bounded_int"
edition = "2023_10"
version = "0.1.0"

[config.override."bounded_int".dependencies.bounded_int]
discriminator = "bounded_int"

[config.override."bounded_int".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false
user_defined_inline_macros = false

[config.override."stwo_cairo_air"]
name = "stwo_cairo_air"
edition = "2024_07"
version = "0.1.0"
cfg_set = [
    ["target", "lib"],
    ["feature", "qm31_opcode"],
    ["feature", "blake_outputs_packing"],
]

[config.override."stwo_cairo_air".dependencies.stwo_cairo_air]
discriminator = "stwo_cairo_air"

[config.override."stwo_cairo_air".dependencies.stwo_constraint_framework]
discriminator = "stwo_constraint_framework"

[config.override."stwo_cairo_air".dependencies.stwo_verifier_core]
discriminator = "stwo_verifier_core"

[config.override."stwo_cairo_air".dependencies.stwo_verifier_utils]
discriminator = "stwo_verifier_utils"

[config.override."stwo_cairo_air".dependencies.bounded_int]
discriminator = "bounded_int"

[config.override."stwo_cairo_air".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false
user_defined_inline_macros = false


[config.override."stwo_constraint_framework"]
name = "stwo_constraint_framework"
edition = "2024_07"
version = "0.1.0"
cfg_set = [
    ["target", "lib"],
    ["feature", "qm31_opcode"],
    ["feature", "blake_outputs_packing"],
]


[config.override."stwo_constraint_framework".dependencies.stwo_constraint_framework]
discriminator = "stwo_constraint_framework"

[config.override."stwo_constraint_framework".dependencies.stwo_verifier_core]
discriminator = "stwo_verifier_core"

[config.override."stwo_constraint_framework".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false
user_defined_inline_macros = false


[config.override."stwo_verifier_core"]
name = "stwo_verifier_core"
edition = "2024_07"
version = "0.1.0"
cfg_set = [
    ["target", "lib"],
    ["feature", "qm31_opcode"],
    ["feature", "blake_outputs_packing"],
]

[config.override."stwo_verifier_core".dependencies.bounded_int]
discriminator = "bounded_int"

[config.override."stwo_verifier_core".dependencies.stwo_verifier_core]
discriminator = "stwo_verifier_core"

[config.override."stwo_verifier_core".dependencies.stwo_verifier_utils]
discriminator = "stwo_verifier_utils"

[config.override."stwo_verifier_core".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false
user_defined_inline_macros = false

[config.override."stwo_verifier_utils"]
name = "stwo_verifier_utils"
edition = "2024_07"
version = "0.1.0"
cfg_set = [
    ["target", "lib"],
    ["feature", "qm31_opcode"],
    ["feature", "blake_outputs_packing"],
]

[config.override."stwo_verifier_utils".dependencies.stwo_verifier_utils]
discriminator = "stwo_verifier_utils"

[config.override."stwo_verifier_utils".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false
user_defined_inline_macros = false

[config.override."stwo_cairo_verifier"]
name = "stwo_cairo_verifier"
edition = "2024_07"
version = "0.1.0"
cfg_set = [
    ["target", "lib"],
    ["feature", "qm31_opcode"],
    ["feature", "blake_outputs_packing"],
]

[config.override."stwo_cairo_verifier".dependencies.stwo_cairo_air]
discriminator = "stwo_cairo_air"

[config.override."stwo_cairo_verifier_mock"]
name = "stwo_cairo_verifier_mock"
edition = "2024_07"
version = "0.1.0"

[config.override."stwo_cairo_verifier_mock".dependencies.stwo_cairo_air]
discriminator = "stwo_cairo_air"

[config.override."stwo_verifier_utils".dependencies.bounded_int]
discriminator = "bounded_int"
