[package]
name = "cairo-air"
version.workspace = true
edition.workspace = true

[dependencies]
itertools.workspace = true
clap.workspace = true
sonic-rs.workspace = true
log.workspace = true
num-traits.workspace = true
paste.workspace = true
# TODO(Ohad): Add parallel config.
stwo-cairo-common.workspace = true
stwo-cairo-adapter.workspace = true
rayon.workspace = true
serde.workspace = true
starknet-curve = "0.5.1"
starknet-ff.workspace = true
starknet-types-core.workspace = true
stwo-cairo-serialize = { path = "../cairo-serialize" }
stwo-prover.workspace = true
stwo-constraint-framework.workspace = true
thiserror.workspace = true
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
rand.workspace = true
