[package]
name = "cairo-prove"
version = "0.1.0"
edition = "2024"

[dependencies]
stwo-cairo-adapter = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "a9d4ad392d0de4a83f2e176e6f9a6f81feb4ecf0", features = [
    "std",
] }
stwo_cairo_prover = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "a9d4ad392d0de4a83f2e176e6f9a6f81feb4ecf0" }
stwo-cairo-serialize = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "a9d4ad392d0de4a83f2e176e6f9a6f81feb4ecf0" }
cairo-air = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "a9d4ad392d0de4a83f2e176e6f9a6f81feb4ecf0" }
cairo-lang-compiler = { git = "https://github.com/starkware-libs/cairo.git", rev = "5cc466a" }
cairo-lang-executable = { git = "https://github.com/starkware-libs/cairo.git", rev = "5cc466a" }
cairo-lang-runner = { git = "https://github.com/starkware-libs/cairo.git", rev = "5cc466a" }
cairo-lang-casm = { git = "https://github.com/starkware-libs/cairo.git", rev = "5cc466a" }
cairo-lang-utils = { git = "https://github.com/starkware-libs/cairo.git", rev = "5cc466a" }
serde_json = "1.0.138"
cairo-vm = { git = "https://github.com/lambdaclass/cairo-vm", rev = "b1a91f929b5fa29a1a2e9e6990a68a1220c0c673", features = [
    "mod_builtin",
] }
clap = { version = "4.5.38", features = ["derive"] }
num-bigint = "0.4.6"
camino = "1.1.9"
log = "0.4.20"
env_logger = "0.11.3"
