[package]
name = "stwo_cairo_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-vm.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
thiserror-no-std.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
