[crate_roots]
"bounded_int" = "/home/ilya/workspaces/stwo-cairo/stwo_cairo_verifier/crates/bounded_int/src"
"stwo_cairo_air" = "/home/ilya/workspaces/stwo-cairo/stwo_cairo_verifier/crates/cairo_air/src"
"stwo_constraint_framework" = "/home/ilya/workspaces/stwo-cairo/stwo_cairo_verifier/crates/constraint_framework/src"
"stwo_verifier_core" = "/home/ilya/workspaces/stwo-cairo/stwo_cairo_verifier/crates/verifier_core/src"

[config.global]
edition = "2024_07"
version = "0.1.0"
cfg_set = [[
    "target",
    "lib",
]]

[config.global.dependencies.bounded_int]
discriminator = "bounded_int"

[config.global.dependencies.stwo_cairo_air]
discriminator = "stwo_cairo_air"

[config.global.dependencies.stwo_constraint_framework]
discriminator = "stwo_constraint_framework"

[config.global.dependencies.stwo_verifier_core]
discriminator = "stwo_verifier_core"

[config.global.experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

[config.override."bounded_int"]
name = "bounded_int"
edition = "2023_10"
version = "0.1.0"

[config.override."bounded_int".dependencies.bounded_int]
discriminator = "bounded_int"

[config.override."bounded_int".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

[config.override."stwo_cairo_air"]
name = "stwo_cairo_air"
edition = "2024_07"
version = "0.1.0"
cfg_set = [[
    "target",
    "lib",
]]

[config.override."stwo_cairo_air".dependencies.stwo_cairo_air]
discriminator = "stwo_cairo_air"

[config.override."stwo_cairo_air".dependencies.stwo_constraint_framework]
discriminator = "stwo_constraint_framework"

[config.override."stwo_cairo_air".dependencies.stwo_verifier_core]
discriminator = "stwo_verifier_core"

[config.override."stwo_cairo_air".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

[config.override."stwo_constraint_framework"]
name = "stwo_constraint_framework"
edition = "2024_07"
version = "0.1.0"

[config.override."stwo_constraint_framework".dependencies.stwo_constraint_framework]
discriminator = "stwo_constraint_framework"

[config.override."stwo_constraint_framework".dependencies.stwo_verifier_core]
discriminator = "stwo_verifier_core"

[config.override."stwo_constraint_framework".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

[config.override."stwo_verifier_core"]
name = "stwo_verifier_core"
edition = "2024_07"
version = "0.1.0"

[config.override."stwo_verifier_core".dependencies.bounded_int]
discriminator = "bounded_int"

[config.override."stwo_verifier_core".dependencies.stwo_verifier_core]
discriminator = "stwo_verifier_core"

[config.override."stwo_verifier_core".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false
