[package]
name = "stwo_cairo_verifier"
version = "0.1.0"
edition = "2024_07"

[lib]
casm = true

[cairo]
inlining-strategy = "avoid"

[tool.fmt]
sort-module-level-items = true

[dependencies]

[dev-dependencies]
cairo_test = "2.8.4"
