[workspace]
members = [
    "crates/bounded_int",
    "crates/cairo_air",
    "crates/cairo_verifier",
    "crates/constraint_framework",
    "crates/verifier_core",
]

[cairo]
enable-gas = false

[dev-dependencies]
cairo_test = "2.11.4"
