[workspace]
members = ["bounded_int"]

[package]
name = "stwo_cairo_verifier"
version = "0.1.0"
edition = "2024_07"

[lib]
casm = true

[cairo]
# TODO(andrew): Remove once inlining bug fixed as increases step counts by about 3x.
inlining-strategy = "avoid"

[tool.fmt]
sort-module-level-items = true

[dependencies]
bounded_int = { path = "bounded_int" }

[dev-dependencies]
cairo_test = "2.8.4"
