[package]
name = "stwo-cairo-serialize-derive"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Derive macros for Stwo Cairo serialization"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = "2.0.90"
