[package]
name = "stwo-cairo-common"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck.workspace = true
itertools.workspace = true
ruint.workspace = true
serde.workspace = true
starknet-ff.workspace = true
starknet-types-core.workspace = true
stwo-cairo-serialize = { path = "../cairo-serialize" }
stwo-prover.workspace = true
serde_arrays.workspace = true
cairo-vm.workspace = true


[dev-dependencies]
rand.workspace = true
